### ISSUE TITLE
[Create new safe] 2 transactions after rejecting the the first one

### ISSUE THREAD

**Issue by GermaVinsmoke** [safe-global/web-core#1913] opened 2023-04-26 13:19 UTC
## Bug description

At create new safe step, it's showing 2 transactions after rejecting it for the first time.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Click on Create new safe
 2. Give your safe a name and then don't fill anything, just click continue
 3. It'll move to next step and open up the Metamask transaction popup
 4. Reject the transaction
 5. Click on Retry button and now it'll show 2 transactions

## Expected result
Should only ask for 1 transaction

## Screenshots
![Screenshot 2023-04-26 at 6 48 12 PM](https://user-images.githubusercontent.com/32815509/234587555-86c89987-8043-493f-a679-2e331d3115de.png)

**Comment by usame-algan** [comment] 2023-04-26 14:26
@GermaVinsmoke thanks for reporting! This is a duplicate of #1881 so I will close this one.

**Closed by usame-algan** 2023-04-26 14:26 UTC
Labels: bug

**Comment by GermaVinsmoke** [comment] 2023-04-26 14:36
Sorry, completely missed it!
