### ISSUE TITLE
Add network switch button to modals

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1225] opened 2022-11-23 07:25 UTC
## What is the feature about

When connected to the wrong chain, we should a button in the header but it would also be helpful to have one within related modals (`SignOrExecuteForm`) in order to not cancel transaction flows.

## The list of requirements

- Add button to `SignOrExecuteForm` when `isWrongChain`

## Designs/sketches

tbd

## Links

- [Feature request thread](https://5afe.slack.com/archives/C03DAGWJCR5/p1669146223597379)

## Screenshots

![image](https://user-images.githubusercontent.com/20442784/203491672-0e89065d-6abe-41f4-a79d-bdd8fed82a86.png)

**Comment by katspaugh** [comment] 2023-02-07 10:25
This can be trivially solved by replacing the Submit button with a Switch Network button in that scenario.

**Comment by qqqzhch** [comment] 2023-03-11 02:34
@ katspaugh  
How can I reproduce this problem? When I send a transaction to the preview page, and I switch the network to an unsupported network, the page automatically detects the network and jumps to the home page
I can't find such a dialog box
![image](https://user-images.githubusercontent.com/3917994/224460306-c56ed269-4e0f-4f45-bbe7-183eec7dff79.png)

**Comment by katspaugh** [comment] 2023-03-11 05:34
Closing this issue because it will be solved differently in https://github.com/safe-global/web-core/pull/1746
Thanks for checking it, @qqqzhch!

**Closed by katspaugh** 2023-03-11 05:34 UTC
Labels: enhancement, good first issue
