### ISSUE TITLE
[Queued/History list] the header with tabs should not be scrollable

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#674] opened 2022-09-27 07:20 UTC
## Bug description
Fix header with tabs
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/history
 2. scroll the list down

Current result: the header is scrolled too
So if the list scrilled down and you need to come back to the queued list from the history , additional steps are required
https://www.loom.com/share/4e795a43bc294a93b41183cbaab4ba10
## Expected result
Fix the header with tabs

**Comment by usame-algan** [comment] 2022-09-27 07:40
The header with tabs should scroll now after https://github.com/safe-global/web-core/pull/626

**Comment by iamacook** [comment] 2022-09-27 07:40
I merged the new page headers this morning. This looks like a caching issue.

**Comment by iamacook** [comment] 2022-09-27 08:02
Confirmed working.

**Closed by iamacook** 2022-09-27 08:02 UTC
Labels: bug, minor
