### ISSUE TITLE
Speeding up tx causes a duplicate

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#620] opened 2022-09-23 08:54 UTC
## Bug description
After speeding up a tx that was taking too long ~showed that the tx end up being replaced, but now there is the same tx in history and queue at the same time~ got an error saying that the tx was unsucessful and was also replaced.
The safe: https://web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions/history

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby

## Steps to reproduce
 1. Go to a Safe 2/x
 2. Create a tx to queue it
 3. Sign it with the 2nd owner but in adv options set a low gas price and fee (0.0000001)
 4. Wait for a bit, the tx will get "stuck" in processing
 5. After a few mins open your MM extension and Speed up the tx with a high gas fee value

## Expected result
The original tx gets executed and no error is shown.

## Obtained result
* An error saying that the tx was unsucessful and was also replaced.
* The tx is now both in the history and queue tabs (same nonce)

## Screenshots
![tx queue](https://user-images.githubusercontent.com/4503659/191925583-c0614b4f-b55e-4fc4-9111-7b4b7919cd17.gif)

**Comment by francovenica** [comment] 2022-09-23 08:55
Note, after waiting for a bit I got this message and the tx dissapeared from the queue tab
![image](https://user-images.githubusercontent.com/4503659/191925875-3790485c-d699-4e9f-bcc1-5dea3e50bf09.png)

**Comment by DiogoSoaress** [comment] 2022-09-27 13:01
@francovenica The error handling is addressed in https://github.com/safe-global/web-core/pull/687 but I was not able to reproduce the duplicated tx after several attempts. Do you have a more predictable way to reproduce it?

**Comment by francovenica** [comment] 2022-09-28 01:28
Checked the fix of the error message in the #687 and it looks good (no more error mesage). 

Tried several times again and I couldn't reproduce it again either. The first time the tx was duplicated for a few minutes and then it ended up dissapearing, so maybe it was a fluke.

I'll pass the ticket and check again during regression to see if the duplication happens again

**Comment by DiogoSoaress** [comment] 2022-09-28 08:08
Ok, thanks @francovenica . I will update the issue title to separate this 2 things

**Closed** 2022-09-28 08:44 UTC
Labels: bug, 🧨
